"""Generate HTML model cards from MLflow runs."""
import argparse
import json
import os
from datetime import datetime
from typing import Optional

import mlflow
from jinja2 import Template


# Model card HTML template
MODEL_CARD_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Model Card - {{model_name}} - {{run.run_id}}</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 1200px; margin: 40px auto; padding: 20px; }
        h1 { color: #333; border-bottom: 3px solid #007bff; padding-bottom: 10px; }
        h2 { color: #555; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
        ul { line-height: 1.8; }
        li { margin: 5px 0; }
        .metric-value { font-weight: bold; color: #007bff; }
        img { border: 1px solid #ddd; border-radius: 4px; padding: 5px; margin: 10px 0; }
        .timestamp { color: #666; font-size: 0.9em; }
        .status { padding: 4px 8px; border-radius: 3px; }
        .status-finished { background-color: #d4edda; color: #155724; }
    </style>
</head>
<body>
    <h1>Model Card: {{model_name}}</h1>
    
    <div class="metadata">
        <p><strong>Run ID:</strong> <code>{{run.run_id}}</code></p>
        <p><strong>Status:</strong> <span class="status status-{{run.status|lower}}">{{run.status}}</span></p>
        <p class="timestamp"><strong>Training Start:</strong> {{run.start_time}}</p>
    </div>

    <h2>Performance Metrics</h2>
    <ul>
    {% for k, v in run.metrics.items() %}
        <li>{{k}}: <span class="metric-value">{{v}}</span></li>
    {% endfor %}
    </ul>

    <h2>Hyperparameters</h2>
    <ul>
    {% for k, v in run.params.items() %}
        <li><code>{{k}}</code> = {{v}}</li>
    {% endfor %}
    </ul>

    <h2>Artifacts</h2>
    <ul>
    {% for a in run.artifacts %}
        <li><code>{{a}}</code></li>
    {% endfor %}
    </ul>

    {% if shap_path %}
    <h2>Model Explainability (SHAP)</h2>
    <p>Feature importance analysis using SHAP values:</p>
    <img src="{{shap_path}}" style="max-width:800px" alt="SHAP summary plot">
    {% endif %}

    <h2>Additional Information</h2>
    <p><em>This model card was auto-generated by the MLOps pipeline on {{generation_time}}.</em></p>
</body>
</html>
"""


def load_run_info(run_id: str, tracking_uri: Optional[str] = None) -> dict:
    """Load MLflow run information.
    
    Args:
        run_id: MLflow run ID
        tracking_uri: Optional MLflow tracking URI override
        
    Returns:
        Dict with run metadata, params, metrics, and artifacts
    """
    if tracking_uri:
        mlflow.set_tracking_uri(tracking_uri)
    elif "MLFLOW_TRACKING_URI" in os.environ:
        mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"])
    
    client = mlflow.tracking.MlflowClient()
    run = client.get_run(run_id)
    
    data = {
        "run_id": run.info.run_id,
        "status": run.info.status,
        "start_time": (
            datetime.fromtimestamp(run.info.start_time / 1000).isoformat()
            if run.info.start_time
            else "N/A"
        ),
        "params": run.data.params,
        "metrics": run.data.metrics,
        "artifacts": [f.path for f in client.list_artifacts(run_id)],
    }
    return data


def generate_model_card(
    run_id: str,
    model_name: str,
    shap_path: Optional[str] = None,
    output_path: str = "/opt/airflow/mlops-pipeline/data/model_card.html",
    tracking_uri: Optional[str] = None,
) -> str:
    """Generate an HTML model card.
    
    Args:
        run_id: MLflow run ID
        model_name: Name of the model
        shap_path: Optional path to SHAP visualization
        output_path: Output path for HTML file
        tracking_uri: Optional MLflow tracking URI override
        
    Returns:
        Path to generated model card
    """
    run = load_run_info(run_id, tracking_uri)
    tpl = Template(MODEL_CARD_TEMPLATE)
    
    html = tpl.render(
        model_name=model_name,
        run=run,
        shap_path=shap_path,
        generation_time=datetime.now().isoformat(),
    )
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    
    print(f"[INFO] Model card written to {output_path}")
    return output_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate model card from MLflow run")
    parser.add_argument("--run-id", required=True, help="MLflow run ID")
    parser.add_argument("--model-name", required=True, help="Model name")
    parser.add_argument("--shap-path", help="Optional path to SHAP visualization")
    parser.add_argument(
        "--output",
        default="/opt/airflow/mlops-pipeline/data/model_card.html",
        help="Output path for model card HTML",
    )
    parser.add_argument("--tracking-uri", help="MLflow tracking URI")
    
    args = parser.parse_args()
    
    generate_model_card(
        run_id=args.run_id,
        model_name=args.model_name,
        shap_path=args.shap_path,
        output_path=args.output,
        tracking_uri=args.tracking_uri,
    )
